### ISSUE TITLE
ValueError when using "enumChoices" or "choices"

### ISSUE THREAD

**Issue by robertazzopardi** [adenh93/django-typomatic#28]
I am trying to generate enums for my choice fields in my models, but get a Value error when generate_ts() is called. This is also the case for the example from the README, for both "enumChoices" and "choices"

```
from django_typomatic import ts_interface, generate_ts
from rest_framework import serializers
from django.db import models


class ActionType(models.TextChoices):
    ACTION1 = "Action1", ("Action1")
    ACTION2 = "Action2", ("Action2")
    ACTION3 = "Action3", ("Action3")


class NumberType(models.IntegerChoices):
    LOW = 1
    MEDIUM = 2
    HIGH = 3


@ts_interface('enumChoices')
class ChoiceSerializer(serializers.Serializer):
    action = serializers.ChoiceField(choices=ActionType.choices)
    num = serializers.ChoiceField(choices=NumberType.choices)

generate_ts("some path relative to the root")
```

I get the following stacktrace:

> Exception in thread django-main-thread:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
>     fn(*args, **kwargs)
>   File "/opt/venv/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
>     autoreload.raise_last_exception()
>   File "/opt/venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
>     raise _exception[1]
>   File "/opt/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 398, in execute
>     autoreload.check_errors(django.setup)()
>   File "/opt/venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
>     fn(*args, **kwargs)
>   File "/opt/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/opt/venv/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
>     app_config.ready()
>   File "/app/backend/asset/apps.py", line 9, in ready
>     import backend.asset.serializers
>   File "/app/backend/asset/serializers.py", line 4, in <module>
>     from config.typomatic import generate_ts_types
>   File "/app/config/typomatic.py", line 34, in <module>
>     generate_ts_types()
>   File "/app/config/typomatic.py", line 8, in generate_ts_types
>     generate_ts("./frontend/src/drf.d.ts")
>   File "/opt/venv/lib/python3.11/site-packages/django_typomatic/__init__.py", line 219, in generate_ts
>     enums_string, interfaces = __get_enums_and_interfaces_from_generated(interfaces_enums)
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/venv/lib/python3.11/site-packages/django_typomatic/__init__.py", line 196, in __get_enums_and_interfaces_from_generated
>     interfaces, enums = [list(tup) for tup in zip(*interfaces_enums)]
>     ^^^^^^^^^^^^^^^^^
> ValueError: not enough values to unpack (expected 2, got 0)

I am running all of this in a Docker container, but everything annotated with just `ts_interface` works fine

**Comment by robertazzopardi** [comment]
The new cli fixes the problems I was having, thank you to the devs of that!
